# Support TillSync Development

# GitHub Sponsors (when available)
# github: KebasoMoses

# Patreon (when available)
# patreon: tillsync

# Ko-fi (when available)  
# ko_fi: tillsync

# Custom funding options
custom: ["https://buy.stripe.com/test_placeholder", "M-Pesa: +254 XXX XXX XXX"]